version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog-app-api 
    restart: always
    ports:
      - 8000:3000
    depends_on:
      - postgres
    env_file:
      - .env.dev
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: blog-app-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db